version: '3'

services:
    brevetsapp:
        build: brevetsapp/
        command: python -u flask_brevets.py
        ports:
            - "5000:5000"
        depends_on:
            - db
        environment:
            MONGODB_HOSTNAME: db
    restapi:
        build: api/
        command: python -u api.py
        ports:
            - "5001:5000"
        depends_on:
            - db
        environment:
            MONGODB_HOSTNAME: db
    website:
        build: website/
        command: python -u website.py
        ports:
            - "5002:5000"
        depends_on:
            - restapi
    db:
        image: mongo:latest
